### ISSUE TITLE
一个页面不是有单一表单组成，而是有多个部分组成，比如嵌套el-card这样的，目前的数据结构是否支持

### ISSUE THREAD

**Issue by jtfl2008** [Heqingsong/element-ui-form#1]

**Comment by Heqingsong** [comment]
可以拆解为多个form表单对象进行配置即可 @jtfl2008  例子中我只配置了一个，您可以配置多个，各自处理各自的情况即可。

**Comment by jtfl2008** [comment]
> 可以拆解为多个form表单对象进行配置即可 @jtfl2008 例子中我只配置了一个，您可以配置多个，各自处理各自的情况即可。

您好，如果是配置多个，会有多个表单对象，对于有关联的表单来说，控制表单和验证都是个问题，比如上个表单部分的某个字段控制下个表单部分是否展示，这个使用场景结合我们这边业务来说的，您有没有更好想法。
